name: icepick
channels:
- conda-forge
dependencies:
- python=3.7.3
- jupyterlab=1.0.1
- matplotlib=3.1.1
- descartes=1.1.0
- pandas=0.24.2
- cartopy=0.17.0
- fiona=1.8.4
- shapely=1.6.4
- geopandas=0.5.1
- h5py=2.9.0
- requests=2.22.0
